# build: docker build -t generalmeow/mybind9:<TAG>-arm -f Dockerfile-arm .
# run: docker run -d -p 53:53 --name influxdb generalmeow/mybind9:<TAG>-arm
FROM hypriot/rpi-alpine-scratch
RUN apk update && \
apk upgrade && \
apk add bash && \
MAINTAINER Paul Hoang 2017-01-08
EXPOSE 53
ENTRYPOINT ["/bin/bash"]
