# build: docker build -t generalmeow/mybind9:<TAG>-arm -f Dockerfile-arm .
# run: docker run -d -p 53:53 --name influxdb generalmeow/mybind9:<TAG>-arm
FROM hypriot/rpi-alpine-scratch
RUN apk update && \
apk upgrade && \
apk add bash && \
apk add bind-tools && \
#apk add bind && \
#rm -rf /var/cache/apk/*
apk add bind
MAINTAINER Paul Hoang 2017-01-08
EXPOSE 53 53/udp
CMD ["mkdir", "-p", "/var/cache/bind"] 
ADD ./etc/bind/named.conf /etc/bind/named.conf
ADD ./etc/bind/db.10 /etc/bind/db.10
ADD ./etc/bind/db.paulhoang.com /etc/bind/db.paulhoang.com
ADD ./etc/bind/named.conf.local /etc/bind/named.conf.local
ADD ./etc/bind/named.conf.options /etc/bind/named.conf.options
ENTRYPOINT ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf"]
#CMD ["/bin/bash"]
